# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oppo/PBEM00/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),PBEM00)

ifeq ($(LOCAL_PATH)/radio, $(wildcard $(LOCAL_PATH)/radio))

RADIO_FILES := $(wildcard $(LOCAL_PATH)/radio/*)
$(foreach f, $(notdir $(RADIO_FILES)), \
    $(call add-radio-file,radio/$(f)))
$(call add-radio-file,../../../device/oppo/PBEM00/radio/filesmap)

endif

endif
